# Generated by Django 4.2 on 2023-04-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "path",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("prefix", models.CharField(max_length=255)),
                ("servername", models.CharField(max_length=255)),
                (
                    "shortname",
                    models.CharField(default="video", max_length=255, unique=True),
                ),
            ],
            options={
                "verbose_name_plural": "libraries",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("pid", models.IntegerField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "series_name",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tv.library"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "smb_path",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("watched", models.BooleanField(default=False)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tv.series"
                    ),
                ),
            ],
        ),
    ]
