# Generated by Django 4.2 on 2023-06-06 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tv", "0003_delete_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "smb_path",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("watched", models.BooleanField(default=False)),
                (
                    "library",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tv.library"),
                ),
            ],
            options={
                "ordering": ["smb_path"],
                "abstract": False,
            },
        ),
    ]
