# Generated by Django 4.2 on 2023-06-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tv", "0004_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="watched",
        ),
        migrations.AddField(
            model_name="movie",
            name="last_watched",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date last watched"),
        ),
    ]
